name: flutter_trip
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # base_library基础组建库,包含：
  # Dart 常用工具类库 common_utils，
  # Flutter 常用工具类库 flustars，
  # 网络 dio，
  # 国际化 fluintl。

  # 本地依赖
  #  base_library:
  #      path: ../FlutterRepos/base_library/
  # git依赖
  base_library:
    git:
      url: git://github.com/Sky24n/FlutterRepos.git
      path: base_library
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^0.1.3
  # Flutter 城市列表 https://github.com/flutterchina/azlistview
  azlistview: ^1.0.2
  # https://github.com/flutterchina/dio
  dio: 1.0.13
  r_dart_library: 0.4.0-nullsafety.0
  # https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1
  # https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # https://github.com/Sky24n/sp_util
  sp_util: ^2.0.0
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: 0.22.6
  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.2
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: 2.0.0
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.7.10
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
#    - assets/images/ic_main_studio_default.png
#    - assets/images/ic_main_studio_selected.png
#    - assets/images/2.0x/
#    - assets/images/3.0x/
#    - assets/images/2.0x/ic_main_studio_default.png
#    - assets/images/3.0x/ic_main_studio_default.png
#    - assets/images/2.0x/ic_main_studio_selected.png
#    - assets/images/3.0x/ic_main_studio_selected.png
#    - assets/images/ic_main_session_selected.png
#    - assets/images/ic_main_session_default.png
#    - assets/images/2.0x/ic_main_session_default.png
#    - assets/images/2.0x/ic_main_session_selected.png
#    - assets/images/3.0x/ic_main_session_default.png
#    - assets/images/3.0x/ic_main_session_selected.png
#    - assets/images/2.0x/ic_main_classic_default.png
#    - assets/images/2.0x/ic_main_classic_selected.png
#    - assets/images/3.0x/ic_main_classic_default.png
#    - assets/images/3.0x/ic_main_classic_selected.png
#    - assets/images/ic_main_classic_default.png
#    - assets/images/ic_main_classic_selected.png
#    - assets/images/2.0x/ic_main_my_selected.png
#    - assets/images/2.0x/ic_main_my_default.png
#    - assets/images/3.0x/ic_main_my_selected.png
#    - assets/images/3.0x/ic_main_my_default.png
#    - assets/images/ic_main_my_selected.png
#    - assets/images/ic_main_my_default.png
